### ISSUE TITLE
Install failing, missing or misplaced files

### ISSUE THREAD

**Issue by daden** [rkirov/youtube-app#2]
I cloned the repo and ran into the following: 

1) On running build.sh, it fails on not finding es5build.js in angular2 and rtts_assert. I copied into those locations and then 
2) build.sh errors on not finding ...node_modules/angular2/atscript/src/change_detection/change_detection_jit_generator.map
3) When I run the app (with the missing map as in #2), I'm getting: 

GET http://localhost:8082/es6/src/rtts_assert.js.map 404 (Not Found)
zone.js:461 GET http://localhost:8082/node_modules/angular2/src/core/annotations/events.js 404 (Not Found)zone.js:461 window.(anonymous function).(anonymous function)es6-module-loader-sans-promises.src.js:1293 fes6-module-loader-sans-promises.src.js:1468 $__Object$defineProperty.valuees6-module-loader-sans-promises.src.js:1467 $__Object$defineProperty.valuesystem.src.js:730 $__global.upgradeSystemLoader.e.fetchsystem.src.js:1729 $__global.upgradeSystemLoader.e.fetchsystem.src.js:1826 $__global.upgradeSystemLoader.e.fetches6-module-loader-sans-promises.src.js:255 (anonymous function)zone.js:87 runzone.js:64 zoneBoundFn
zone.js:87 Error loading "angular2/src/core/annotations/events" at http://localhost:8082/node_modules/angular2/src/core/annotations/events.js
Error loading "angular2/src/core/annotations/events" from "main" at http://localhost:8082/main.js
Not Found: http://localhost:8082/node_modules/angular2/src/core/annotations/events.js

**Comment by swirlycheetah** [comment]
I think I'm seeing the same issue, workflow is;

* clone the repository and `cd` into it
* run `./build.sh`

Which returns the following two errors and then seems to get stuck.

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/foo/projects/youtube-app/node_modules/angular2/es5build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/foo/projects/youtube-app/node_modules/rtts_assert/es5build.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

I did try serving the app afterwards just in case but it didn't work.
